services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME:-leads_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-leads_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: ./apps/Dockerfile
      target: production
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    working_dir: /app
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - DB_NAME=${DB_NAME:-leads_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - REDIS_URL=redis://redis:6379/0
    profiles:
      - production

  web-dev:
    build:
      context: .
      dockerfile: ./apps/Dockerfile
      target: development
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    working_dir: /app
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - DB_NAME=${DB_NAME:-leads_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - REDIS_URL=redis://redis:6379/0
    profiles:
      - development

volumes:
  postgres_data:
  redis_data:
